name: Check if GH Agent has bun installed

on:
  workflow_dispatch: {}

jobs:
  bun-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repositories: ["aaa", "bbb"]
    steps:
      - uses: oven-sh/setup-bun@v1
      - run: bun --version
      - run: echo ${{ matrix.repositories }}
