name: Check if GH Agent has bun installed

on:
  workflow_dispatch: {}

jobs:
  bun-test:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - name: Setup git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - run: |
          echo "Hello" >> foo.txt
          git add .
          git commit -m "test: update foo.txt"
          git push
