name: Check Nrwl Set Shas action when run on tag

on:
  workflow_dispatch: {}


jobs:
  test-set-shas:
    name: Test Set SHAs from ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4 #177b48373c6dc583ce0d9257ffb484bdd232fedf #v3.0.2
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Derive Base SHA based on Previous Git Tag
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          # Get the most recent tag for this branch
          RECENT_TAG=$(git describe --abbrev=0 --tags || true)
          if [[ -z "$RECENT_TAG" ]]; then
            echo "::notice:: Recent Tag for branch ${{ github.ref_name }} not found. Not Reseting Base SHA"
            exit 0;
          fi
  
          # Get the previous tag for this branch
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags --exclude="$RECENT_TAG" || true)
  
          if [[ -z "$PREVIOUS_TAG" ]]; then
            echo "::notice:: Previous Tag for branch ${{ github.ref_name }} not found. Not Reseting Base SHA"
            exit 0;
          fi
  
          # Reset BASE_SHA to SHA of the previous tag
          BASE_SHA=$(git rev-list -n 1 $PREVIOUS_TAG)
          echo "::notice:: Setting NX_BASE=$BASE_SHA base on Tag $PREVIOUS_TAG"
          echo "NX_BASE=$BASE_SHA" >> $GITHUB_ENV

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

